# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0.xci
# IP: The module: 'system_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0.xci
# IP: The module: 'system_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/LineArray/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
