# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Translator_v1_0_bfm_1/Translator_v1_0_bfm_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1 || ORIG_REF_NAME==Translator_v1_0_bfm_1}]

# IP: bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_processing_system7_0_0/Translator_v1_0_bfm_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1_processing_system7_0_0 || ORIG_REF_NAME==Translator_v1_0_bfm_1_processing_system7_0_0}]

# IP: bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_ps7_0_axi_periph_0/Translator_v1_0_bfm_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==Translator_v1_0_bfm_1_ps7_0_axi_periph_0}]

# IP: bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_rst_ps7_0_50M_0/Translator_v1_0_bfm_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==Translator_v1_0_bfm_1_rst_ps7_0_50M_0}]

# IP: bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_Translator_1_0/Translator_v1_0_bfm_1_Translator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1_Translator_1_0 || ORIG_REF_NAME==Translator_v1_0_bfm_1_Translator_1_0}]

# IP: bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_auto_pc_0/Translator_v1_0_bfm_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Translator_v1_0_bfm_1_auto_pc_0 || ORIG_REF_NAME==Translator_v1_0_bfm_1_auto_pc_0}]

# XDC: bd/Translator_v1_0_bfm_1/Translator_v1_0_bfm_1_ooc.xdc
