# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.cache/wt [current_project]
set_property parent.project_path C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/Mykho/Documents/repos/LineArrayZybo/ip_repo/Translator_1.0
  c:/Users/Mykho/Documents/repos/LineArrayZybo/ip_repo/test3_1.0
  c:/Users/Mykho/Documents/repos/LineArrayZybo/ip_repo/axi-lite-test2_1.0
  c:/Users/Mykho/Documents/repos/LineArrayZybo/ip_repo/AXI_Lite_test_1.0
} [current_project]
set_property ip_output_repo c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/hdl/Translator_v1_0_bfm_1_wrapper.vhd
add_files C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/Translator_v1_0_bfm_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_processing_system7_0_0/Translator_v1_0_bfm_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_rst_ps7_0_50M_0/Translator_v1_0_bfm_1_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_rst_ps7_0_50M_0/Translator_v1_0_bfm_1_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_rst_ps7_0_50M_0/Translator_v1_0_bfm_1_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/ip/Translator_v1_0_bfm_1_auto_pc_0/Translator_v1_0_bfm_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/Translator_v1_0_bfm_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/Translator_v1_0_bfm_1/Translator_v1_0_bfm_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Translator_v1_0_bfm_1_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef Translator_v1_0_bfm_1_wrapper.dcp

catch { report_utilization -file Translator_v1_0_bfm_1_wrapper_utilization_synth.rpt -pb Translator_v1_0_bfm_1_wrapper_utilization_synth.pb }
