# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_SystemReset_0_0/system_SystemReset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_SystemReset_0_0 || ORIG_REF_NAME==system_SystemReset_0_0}]

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0}]

# IP: bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_0_0 || ORIG_REF_NAME==system_fir_compiler_0_0}]

# IP: bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_1_0 || ORIG_REF_NAME==system_fir_compiler_1_0}]

# IP: bd/system/ip/system_fir_compiler_2_0/system_fir_compiler_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_2_0 || ORIG_REF_NAME==system_fir_compiler_2_0}]

# IP: bd/system/ip/system_fir_compiler_3_0/system_fir_compiler_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_3_0 || ORIG_REF_NAME==system_fir_compiler_3_0}]

# IP: bd/system/ip/system_fir_compiler_4_0/system_fir_compiler_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_4_0 || ORIG_REF_NAME==system_fir_compiler_4_0}]

# IP: bd/system/ip/system_fir_compiler_5_0/system_fir_compiler_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_5_0 || ORIG_REF_NAME==system_fir_compiler_5_0}]

# IP: bd/system/ip/system_fir_compiler_6_0/system_fir_compiler_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_6_0 || ORIG_REF_NAME==system_fir_compiler_6_0}]

# IP: bd/system/ip/system_fir_compiler_7_0/system_fir_compiler_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_7_0 || ORIG_REF_NAME==system_fir_compiler_7_0}]

# IP: bd/system/ip/system_fir_compiler_8_0/system_fir_compiler_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_compiler_8_0 || ORIG_REF_NAME==system_fir_compiler_8_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_0_2/system_PWM_GENERATOR_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_0_2 || ORIG_REF_NAME==system_PWM_GENERATOR_0_2}]

# IP: bd/system/ip/system_PWM_GENERATOR_1_0/system_PWM_GENERATOR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_1_0 || ORIG_REF_NAME==system_PWM_GENERATOR_1_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_2_0/system_PWM_GENERATOR_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_2_0 || ORIG_REF_NAME==system_PWM_GENERATOR_2_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_3_0/system_PWM_GENERATOR_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_3_0 || ORIG_REF_NAME==system_PWM_GENERATOR_3_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_4_0/system_PWM_GENERATOR_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_4_0 || ORIG_REF_NAME==system_PWM_GENERATOR_4_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_5_0/system_PWM_GENERATOR_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_5_0 || ORIG_REF_NAME==system_PWM_GENERATOR_5_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_6_0/system_PWM_GENERATOR_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_6_0 || ORIG_REF_NAME==system_PWM_GENERATOR_6_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_7_0/system_PWM_GENERATOR_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_7_0 || ORIG_REF_NAME==system_PWM_GENERATOR_7_0}]

# IP: bd/system/ip/system_PWM_GENERATOR_8_0/system_PWM_GENERATOR_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PWM_GENERATOR_8_0 || ORIG_REF_NAME==system_PWM_GENERATOR_8_0}]

# IP: bd/system/ip/system_all_pass_filter_0_0/system_all_pass_filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_all_pass_filter_0_0 || ORIG_REF_NAME==system_all_pass_filter_0_0}]

# IP: bd/system/ip/system_DelayUnit_0_0/system_DelayUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_DelayUnit_0_0 || ORIG_REF_NAME==system_DelayUnit_0_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0}]

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_translatorV2_v1_0_0_0/system_translatorV2_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_translatorV2_v1_0_0_0 || ORIG_REF_NAME==system_translatorV2_v1_0_0_0}]

# IP: bd/system/ip/system_SpeakerGain_v1_0_0_1/system_SpeakerGain_v1_0_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_SpeakerGain_v1_0_0_1 || ORIG_REF_NAME==system_SpeakerGain_v1_0_0_1}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/system_ooc.xdc
