# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/EAAES/asignments/LineArray/LineArray.cache/wt [current_project]
set_property parent.project_path C:/EAAES/asignments/LineArray/LineArray.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/EAAES/asignments/ip_repo/translatorV2_1.0 [current_project]
set_property ip_output_repo c:/EAAES/asignments/LineArray/LineArray.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/hdl/system_wrapper.vhd
add_files C:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_0_0/system_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_2_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_2_0/system_fir_compiler_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_3_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_3_0/system_fir_compiler_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_4_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_4_0/system_fir_compiler_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_5_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_5_0/system_fir_compiler_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_6_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_6_0/system_fir_compiler_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_7_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_7_0/system_fir_compiler_7_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_8_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_fir_compiler_8_0/system_fir_compiler_8_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/EAAES/asignments/LineArray/LineArray.srcs/sources_1/bd/system/system.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/EAAES/asignments/LineArray/LineArray.srcs/constrs_1/new/constrains.xdc
set_property used_in_implementation false [get_files C:/EAAES/asignments/LineArray/LineArray.srcs/constrs_1/new/constrains.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
