# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0.xci
# IP: The module: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Mykho/Documents/repos/LineArrayZybo/axi_peripheral/axi_peripheral.srcs/sources_1/bd/AXI_Lite_test_v1_0_bfm_1/ip/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0/AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Lite_test_v1_0_bfm_1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
